# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2baf36d761d4d7305ba15a99c420c44a3f746966511cf8782b57625f82510653e3625a9ed8ca602e91f47f7ff4a1a4150e28c2e17b0c21ae9b98ebd9a9450a75

test:
  secret_key_base: c3d73f13253cd54c25578d28c68bea6e1219e348aed69b2605340f6c5bed26f25d82f78f5ea54df7938aa09d1158fb02df088e72c78d17fbde1802b72696aab3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
